# Generated by Django 5.1.1 on 2024-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="documentation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
