# Generated by Django 5.1.1 on 2024-10-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
